name = "dcf77vfd"
description = "Ma_Sys.ma DCF77 VFD Module Clock - Raspberry Pi Pico Ada Incarnation"
version = "1.0.0"

authors = ["Linux-Fan"]
maintainers = ["Linux-Fan <Ma_Sys.ma@web.de>"]
maintainers-logins = ["m7a"]

executables = ["dcf77vfd"]
[[depends-on]]
pico_bsp = "^2.0.0"
