compile:
	javac ArrayFromImage.java

run:
	java ArrayFromImage f1.png 8 16 "!\"#\$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_\`abcdefghijklmnopqrstuvwxyz{|}~ €?????????????????" > f1.c
	java ArrayFromImage f2.png 16 32 "0123456789.:/-(!)*#     " > f2.c
